import { it, expect, vi, beforeAll, afterAll, describe } from 'vitest';
import getMonthInfo from '../utils/getMonthInfo';

beforeAll(() => {
  vi.useFakeTimers().setSystemTime(new Date('2001-04-04'));
});
afterAll(() => {
  vi.useRealTimers();
});

it('no args', () => {
  const expectedResult = [
    {
      year: 2001,
      month: 3,
      day: 1,
      weekDayName: 'SUN',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 2,
      weekDayName: 'MON',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 3,
      weekDayName: 'TUE',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 4,
      weekDayName: 'WED',
      isCurrentDay: true,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 5,
      weekDayName: 'THU',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 6,
      weekDayName: 'FRI',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 7,
      weekDayName: 'SAT',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 8,
      weekDayName: 'SUN',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 9,
      weekDayName: 'MON',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 10,
      weekDayName: 'TUE',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 11,
      weekDayName: 'WED',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 12,
      weekDayName: 'THU',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 13,
      weekDayName: 'FRI',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 14,
      weekDayName: 'SAT',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 15,
      weekDayName: 'SUN',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 16,
      weekDayName: 'MON',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 17,
      weekDayName: 'TUE',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 18,
      weekDayName: 'WED',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 19,
      weekDayName: 'THU',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 20,
      weekDayName: 'FRI',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 21,
      weekDayName: 'SAT',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 22,
      weekDayName: 'SUN',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 23,
      weekDayName: 'MON',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 24,
      weekDayName: 'TUE',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 25,
      weekDayName: 'WED',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 26,
      weekDayName: 'THU',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 27,
      weekDayName: 'FRI',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 28,
      weekDayName: 'SAT',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 29,
      weekDayName: 'SUN',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 3,
      day: 30,
      weekDayName: 'MON',
      isCurrentDay: false,
      isCurrentMonth: true,
    },
    {
      year: 2001,
      month: 4,
      day: 1,
      weekDayName: 'TUE',
      isCurrentDay: false,
      isCurrentMonth: false,
    },
    {
      year: 2001,
      month: 4,
      day: 2,
      weekDayName: 'WED',
      isCurrentDay: false,
      isCurrentMonth: false,
    },
    {
      year: 2001,
      month: 4,
      day: 3,
      weekDayName: 'THU',
      isCurrentDay: false,
      isCurrentMonth: false,
    },
    {
      year: 2001,
      month: 4,
      day: 4,
      weekDayName: 'FRI',
      isCurrentDay: false,
      isCurrentMonth: false,
    },
    {
      year: 2001,
      month: 4,
      day: 5,
      weekDayName: 'SAT',
      isCurrentDay: false,
      isCurrentMonth: false,
    },
    {
      year: 2001,
      month: 4,
      day: 6,
      weekDayName: 'SUN',
      isCurrentDay: false,
      isCurrentMonth: false,
    },
    {
      year: 2001,
      month: 4,
      day: 7,
      weekDayName: 'MON',
      isCurrentDay: false,
      isCurrentMonth: false,
    },
    {
      year: 2001,
      month: 4,
      day: 8,
      weekDayName: 'TUE',
      isCurrentDay: false,
      isCurrentMonth: false,
    },
    {
      year: 2001,
      month: 4,
      day: 9,
      weekDayName: 'WED',
      isCurrentDay: false,
      isCurrentMonth: false,
    },
    {
      year: 2001,
      month: 4,
      day: 10,
      weekDayName: 'THU',
      isCurrentDay: false,
      isCurrentMonth: false,
    },
    {
      year: 2001,
      month: 4,
      day: 11,
      weekDayName: 'FRI',
      isCurrentDay: false,
      isCurrentMonth: false,
    },
    {
      year: 2001,
      month: 4,
      day: 12,
      weekDayName: 'SAT',
      isCurrentDay: false,
      isCurrentMonth: false,
    },
  ];
  expect(expectedResult).toEqual(getMonthInfo());
});
describe('week offset', () => {
  it('positive', () => {
    const expectedResult = [
      {
        year: 2001,
        month: 3,
        day: 1,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 2,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 3,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 4,
        weekDayName: 'WED',
        isCurrentDay: true,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 5,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 6,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 7,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 8,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 9,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 10,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 11,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 12,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 13,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 14,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 15,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 16,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 17,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 18,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 19,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 20,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 21,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 22,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 23,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 24,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 25,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 26,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 27,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 28,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 29,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 30,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 1,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 2,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 3,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 4,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 5,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 6,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 7,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 8,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 9,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 10,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 11,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 12,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
    ];
    expect(expectedResult).toEqual(getMonthInfo(undefined, 1));
  });
  it('negative', () => {
    const expectedResult = [
      {
        year: 2001,
        month: 1,
        day: 25,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 1,
        day: 26,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 1,
        day: 27,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 1,
        day: 28,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 2,
        day: 1,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 2,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 3,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 4,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 5,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 6,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 7,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 8,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 9,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 10,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 11,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 12,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 13,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 14,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 15,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 16,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 17,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 18,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 19,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 20,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 21,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 22,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 23,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 24,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 25,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 26,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 27,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 28,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 29,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 30,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 31,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 1,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 2,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 3,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 4,
        weekDayName: 'WED',
        isCurrentDay: true,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 5,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 6,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 7,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
    ];
    expect(expectedResult).toEqual(getMonthInfo(undefined, -1));
  });
});
describe('month offset', () => {
  it('positive', () => {
    const expectedResult = [
      {
        year: 2001,
        month: 3,
        day: 29,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 30,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 1,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 2,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 3,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 4,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 5,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 6,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 7,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 8,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 9,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 10,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 11,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 12,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 13,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 14,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 15,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 16,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 17,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 18,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 19,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 20,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 21,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 22,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 23,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 24,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 25,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 26,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 27,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 28,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 29,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 30,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 31,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 5,
        day: 1,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 5,
        day: 2,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 5,
        day: 3,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 5,
        day: 4,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 5,
        day: 5,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 5,
        day: 6,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 5,
        day: 7,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 5,
        day: 8,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 5,
        day: 9,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
    ];
    expect(expectedResult).toEqual(getMonthInfo(1));
  });
  it('negative', () => {
    const expectedResult = [
      {
        year: 2001,
        month: 1,
        day: 25,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 1,
        day: 26,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 1,
        day: 27,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 1,
        day: 28,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 2,
        day: 1,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 2,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 3,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 4,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 5,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 6,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 7,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 8,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 9,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 10,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 11,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 12,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 13,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 14,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 15,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 16,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 17,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 18,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 19,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 20,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 21,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 22,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 23,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 24,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 25,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 26,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 27,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 28,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 29,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 30,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 31,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 1,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 2,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 3,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 4,
        weekDayName: 'WED',
        isCurrentDay: true,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 5,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 6,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 7,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
    ];
    expect(expectedResult).toEqual(getMonthInfo(-1));
  });
});
describe('both offsets', () => {
  it('both positive', () => {
    const expectedResult = [
      {
        year: 2001,
        month: 3,
        day: 29,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 30,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 1,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 2,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 3,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 4,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 5,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 6,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 7,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 8,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 9,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 10,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 11,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 12,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 13,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 14,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 15,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 16,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 17,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 18,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 19,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 20,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 21,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 22,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 23,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 24,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 25,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 26,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 27,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 28,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 29,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 30,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 31,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 5,
        day: 1,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 5,
        day: 2,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 5,
        day: 3,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 5,
        day: 4,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 5,
        day: 5,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 5,
        day: 6,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 5,
        day: 7,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 5,
        day: 8,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 5,
        day: 9,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
    ];
    expect(expectedResult).toEqual(getMonthInfo(1, 1));
  });
  it('both negative', () => {
    const expectedResult = [
      {
        year: 2001,
        month: 0,
        day: 28,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 0,
        day: 29,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 0,
        day: 30,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 0,
        day: 31,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 1,
        day: 1,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 2,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 3,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 4,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 5,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 6,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 7,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 8,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 9,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 10,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 11,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 12,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 13,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 14,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 15,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 16,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 17,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 18,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 19,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 20,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 21,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 22,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 23,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 24,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 25,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 26,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 27,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 1,
        day: 28,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 1,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 2,
        day: 2,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 2,
        day: 3,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 2,
        day: 4,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 2,
        day: 5,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 2,
        day: 6,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 2,
        day: 7,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 2,
        day: 8,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 2,
        day: 9,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 2,
        day: 10,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
    ];
    expect(expectedResult).toEqual(getMonthInfo(-1, -1));
  });
  it('month negative, week positive', () => {
    const expectedResult = [
      {
        year: 2001,
        month: 1,
        day: 25,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 1,
        day: 26,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 1,
        day: 27,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 1,
        day: 28,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 2,
        day: 1,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 2,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 3,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 4,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 5,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 6,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 7,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 8,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 9,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 10,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 11,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 12,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 13,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 14,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 15,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 16,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 17,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 18,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 19,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 20,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 21,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 22,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 23,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 24,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 25,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 26,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 27,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 28,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 29,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 30,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 2,
        day: 31,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 1,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 2,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 3,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 4,
        weekDayName: 'WED',
        isCurrentDay: true,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 5,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 6,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 3,
        day: 7,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
    ];
    expect(expectedResult).toEqual(getMonthInfo(-1, 1));
  });
  it('month positive, week negative', () => {
    const expectedResult = [
      {
        year: 2001,
        month: 3,
        day: 1,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 2,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 3,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 4,
        weekDayName: 'WED',
        isCurrentDay: true,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 5,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 6,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 7,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 8,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 9,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 10,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 11,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 12,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 13,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 14,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 15,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 16,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 17,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 18,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 19,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 20,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 21,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 22,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 23,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 24,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 25,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 26,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 27,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 28,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 29,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 3,
        day: 30,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: true,
      },
      {
        year: 2001,
        month: 4,
        day: 1,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 2,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 3,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 4,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 5,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 6,
        weekDayName: 'SUN',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 7,
        weekDayName: 'MON',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 8,
        weekDayName: 'TUE',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 9,
        weekDayName: 'WED',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 10,
        weekDayName: 'THU',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 11,
        weekDayName: 'FRI',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
      {
        year: 2001,
        month: 4,
        day: 12,
        weekDayName: 'SAT',
        isCurrentDay: false,
        isCurrentMonth: false,
      },
    ];
    expect(expectedResult).toEqual(getMonthInfo(1, -1));
  });
});
